In [1]:
import pandas as pd
import warnings
from IPython.utils import io
import sys
warnings.filterwarnings('ignore')
pd.set_option('display.max_columns', None)
#pd.set_option('display.max_rows', None)

## **Load, format, and examine 'prds_hosp10_yr' sas7bdat files**
## Concatenate files into a single dataframe (main_df) and join with the crosswalk file

In [2]:
with io.capture_output() as captured: prds_2010_df = pd.read_sas('~/GitHub/HCRIS-databuilder/hosp10-sas/prds_hosp10_yr2010.sas7bdat')
prds_2010_df['File Date'] = ['2010'] * prds_2010_df.shape[0]
print('prds_hosp10_yr2010: (rows, columns) =', prds_2010_df.shape)

with io.capture_output() as captured: prds_2011_df = pd.read_sas('~/GitHub/HCRIS-databuilder/hosp10-sas/prds_hosp10_yr2011.sas7bdat')
prds_2011_df['File Date'] = ['2011'] * prds_2011_df.shape[0]
print('prds_hosp10_yr2011: (rows, columns) =', prds_2011_df.shape)

with io.capture_output() as captured: prds_2012_df = pd.read_sas('~/GitHub/HCRIS-databuilder/hosp10-sas/prds_hosp10_yr2012.sas7bdat')
prds_2012_df['File Date'] = ['2012'] * prds_2012_df.shape[0]
print('prds_hosp10_yr2012: (rows, columns) =', prds_2012_df.shape)

with io.capture_output() as captured: prds_2013_df = pd.read_sas('~/GitHub/HCRIS-databuilder/hosp10-sas/prds_hosp10_yr2013.sas7bdat')
prds_2013_df['File Date'] = ['2013'] * prds_2013_df.shape[0]
print('prds_hosp10_yr2013: (rows, columns) =', prds_2013_df.shape)

with io.capture_output() as captured: prds_2014_df = pd.read_sas('~/GitHub/HCRIS-databuilder/hosp10-sas/prds_hosp10_yr2014.sas7bdat')
prds_2014_df['File Date'] = ['2014'] * prds_2014_df.shape[0]
print('prds_hosp10_yr2014: (rows, columns) =', prds_2014_df.shape)

with io.capture_output() as captured: prds_2015_df = pd.read_sas('~/GitHub/HCRIS-databuilder/hosp10-sas/prds_hosp10_yr2015.sas7bdat')
prds_2015_df['File Date'] = ['2015'] * prds_2015_df.shape[0]
print('prds_hosp10_yr2015: (rows, columns) =', prds_2015_df.shape)

with io.capture_output() as captured: prds_2016_df = pd.read_sas('~/GitHub/HCRIS-databuilder/hosp10-sas/prds_hosp10_yr2016.sas7bdat')
prds_2016_df['File Date'] = ['2016'] * prds_2016_df.shape[0]
print('prds_hosp10_yr2016: (rows, columns) =', prds_2016_df.shape)

with io.capture_output() as captured: prds_2017_df = pd.read_sas('~/GitHub/HCRIS-databuilder/hosp10-sas/prds_hosp10_yr2017.sas7bdat')
prds_2017_df['File Date'] = ['2017'] * prds_2017_df.shape[0]
print('prds_hosp10_yr2017: (rows, columns) =', prds_2017_df.shape)

with io.capture_output() as captured: prds_2018_df = pd.read_sas('~/GitHub/HCRIS-databuilder/hosp10-sas/prds_hosp10_yr2018.sas7bdat')
prds_2018_df['File Date'] = ['2018'] * prds_2018_df.shape[0]
print('prds_hosp10_yr2018: (rows, columns) =', prds_2018_df.shape)

with io.capture_output() as captured: prds_2019_df = pd.read_sas('~/GitHub/HCRIS-databuilder/hosp10-sas/prds_hosp10_yr2019.sas7bdat')
prds_2019_df['File Date'] = ['2019'] * prds_2019_df.shape[0]
print('prds_hosp10_yr2019: (rows, columns) =', prds_2019_df.shape)

with io.capture_output() as captured: prds_2020_df = pd.read_sas('~/GitHub/HCRIS-databuilder/hosp10-sas/prds_hosp10_yr2020.sas7bdat')
prds_2020_df['File Date'] = ['2020'] * prds_2020_df.shape[0]
print('prds_hosp10_yr2020: (rows, columns) =', prds_2020_df.shape)

with io.capture_output() as captured: prds_2021_df = pd.read_sas('~/GitHub/HCRIS-databuilder/hosp10-sas/prds_hosp10_yr2021.sas7bdat')
prds_2021_df['File Date'] = ['2021'] * prds_2021_df.shape[0]
print('prds_hosp10_yr2021: (rows, columns) =', prds_2021_df.shape)

with io.capture_output() as captured: prds_2022_df = pd.read_sas('~/GitHub/HCRIS-databuilder/hosp10-sas/prds_hosp10_yr2022.sas7bdat')
prds_2022_df['File Date'] = ['2022'] * prds_2022_df.shape[0]
print('prds_hosp10_yr2022: (rows, columns) =', prds_2022_df.shape)

prds_hosp10_yr2010: (rows, columns) = (2323, 5522)
prds_hosp10_yr2011: (rows, columns) = (6150, 5522)
prds_hosp10_yr2012: (rows, columns) = (6227, 5522)
prds_hosp10_yr2013: (rows, columns) = (6248, 5522)
prds_hosp10_yr2014: (rows, columns) = (6250, 5522)
prds_hosp10_yr2015: (rows, columns) = (6257, 5522)
prds_hosp10_yr2016: (rows, columns) = (6211, 5522)
prds_hosp10_yr2017: (rows, columns) = (6173, 5522)
prds_hosp10_yr2018: (rows, columns) = (6159, 5522)
prds_hosp10_yr2019: (rows, columns) = (6118, 5522)
prds_hosp10_yr2020: (rows, columns) = (6050, 5522)
prds_hosp10_yr2021: (rows, columns) = (2597, 5522)
prds_hosp10_yr2022: (rows, columns) = (5, 5522)

In [3]:
main_df = pd.concat([prds_2022_df, prds_2021_df, prds_2020_df, prds_2019_df, prds_2018_df, prds_2017_df, prds_2016_df, 
                     prds_2015_df, prds_2014_df, prds_2013_df, prds_2012_df, prds_2011_df, prds_2010_df,
                     ], ignore_index=True)

main_df = main_df.applymap(lambda x: x.decode() if isinstance(x, bytes) else x)
print('main_df.shape:', main_df.shape)

main_df.shape: (66768, 5522)

In [4]:
to_replace = ['rpt_rec_num', 'prvdr_num', 'fi_num', 'rpt_stus_cd', 'fi_creat_dt', 
              'fy_bgn_dt', 'fy_end_dt', 'util_cd', 'trnsmtl_num', 'state', 
              'st_cty_cd', 'census', 'region', 'proc_dt', 'msa', 'H3_1_HHA1_C10_15____',
              'H3_1_HHA1_C11_15____', 'sub3', 
             ]

replacement = ['RPT_REC_NUM', 'PRVDR_NUM', 'FI_NUM', 'RPT_STUS_CD', 'FI_CREAT_DT', 
               'FY_BGN_DT', 'FY_END_DT', 'UTIL_CODE', 'TRNSMTL_NUM', 'STATE', 
               'ST_CTY_CD', 'CENSUS', 'REGION', 'PROC_DT', 'MSA', 'H3_1_HHA1_C10_15',
               'H3_1_HHA1_C11_15', 'SUB3',
              ]

main_df.rename(columns = {to_replace[0]: replacement[0], to_replace[1]: replacement[1],
                           to_replace[2]: replacement[2], to_replace[3]: replacement[3],
                           to_replace[4]: replacement[4], to_replace[5]: replacement[5],
                           to_replace[6]: replacement[6], to_replace[7]: replacement[7],
                           to_replace[8]: replacement[8], to_replace[9]: replacement[9],
                           to_replace[10]: replacement[10], to_replace[11]: replacement[11],
                           to_replace[12]: replacement[12], to_replace[13]: replacement[13],
                           to_replace[14]: replacement[14], to_replace[15]: replacement[15],
                           to_replace[16]: replacement[16], to_replace[17]: replacement[17],
                         }, inplace = True)

main_df.drop(['_NAME_'], axis=1, inplace=True)
print('main_df.shape:', main_df.shape)

main_df.shape: (66768, 5521)

In [5]:
crosswalk_df = pd.read_csv('~/GitHub/HCRIS-databuilder/crosswalk/2552-10 SAS FILE RECORD LAYOUT AND CROSSWALK TO 96 - 2021.csv', sep=',')
crosswalk_labels = crosswalk_df['10_FIELD_NAME'].tolist()
crosswalk_labels = [str(x).strip(' ') for x in crosswalk_labels]
crosswalk_df['10_FIELD_NAME'] = crosswalk_labels

In [6]:
main_df_col_labels = list(main_df)
main_df_col_labels = [str(x).strip(' ') for x in main_df_col_labels]

print('\nNumber of labels in the crosswalk:', len(crosswalk_labels))
print('Number of unique labels in the crosswalk:', len(list(set(crosswalk_labels))))

print('\nNumber of labels in the main_df:', len(main_df_col_labels))
print('Number of unique labels in the main_df:', len(list(set(main_df_col_labels))))

shared_labels = list(set(main_df_col_labels) & set(crosswalk_labels))
print('\nNumber of labels shared between the main dataframe and the crosswalk:', len(shared_labels))
shared_labels.append('File Date')

dif = set(main_df_col_labels).difference(crosswalk_labels)
print('\n' + str(len(dif)) + ' labels in main dataframe but not in crosswalk:')
print(dif)

dif = set(crosswalk_labels).difference(main_df_col_labels)
print('\n' + str(len(dif)) + ' labels in crosswalk but not in main dataframe:')
print(dif)

Number of labels in the crosswalk: 5571
Number of unique labels in the crosswalk: 5516

Number of labels in the main_df: 5521
Number of unique labels in the main_df: 5521

Number of labels shared between the main dataframe and the crosswalk: 5514

7 labels in main dataframe but not in crosswalk:
{'S3_1_C14_4', 'File Date', 'S3_1_C8_3201', 'S3_1_C14_2', 'PROC_DT', 'S3_1_C14_3', 'S2_1_C2_22'}

2 labels in crosswalk but not in main dataframe:
{'nan', 'NOT ON FORM'}

In [7]:
main_df2 = main_df[main_df.columns[main_df.columns.isin(shared_labels)]]
main_df2 = main_df2.dropna(axis=1, how='all')
main_df2 = main_df2.dropna(axis=0, how='all')
print('main_df2.shape (columns and rows with no data removed):', main_df2.shape)

CODE = []
FIELD_DESCRIPTION = []
TYPE = []
SUBTYPE = []

col_labels = list(main_df2)
for lab in col_labels:
    if lab == 'File Date':
        CODE.append('File Date')
        FIELD_DESCRIPTION.append('File Date')
        TYPE.append('File Date')
        SUBTYPE.append('File Date')
    else:
        df_sub = crosswalk_df[crosswalk_df['10_FIELD_NAME'] == lab]
        CODE.append(df_sub['10_FIELD_NAME'].iloc[0])
        
        x = df_sub['FIELD DESCRIPTION '].iloc[0]
        if x == "" or pd.isnull(x):
            FIELD_DESCRIPTION.append('No Description')
            
        else:
            FIELD_DESCRIPTION.append(x)
        
        x = df_sub['TYPE'].iloc[0]
        if x == "" or pd.isnull(x):
            TYPE.append('No Description')
        else:
            TYPE.append(x)
        
        x = df_sub['SUBTYPE'].iloc[0]
        if x == "" or pd.isnull(x):
                SUBTYPE.append('')
        else:
            SUBTYPE.append(x)

SUBTYPE = pd.Series(SUBTYPE).fillna('').tolist()
TYPE = pd.Series(TYPE).fillna('').tolist()

for i, val in enumerate(SUBTYPE):
    if val == 'File Date':
        continue
    elif val == '':
        SUBTYPE[i] = str(FIELD_DESCRIPTION[i]) + ' ' + '(' + str(CODE[i]) + ')'
    else:
        SUBTYPE[i] = str(val) + ' ' + str(FIELD_DESCRIPTION[i]) + ' (' + str(CODE[i]) + ')'

main_df2.shape (columns and rows with no data removed): (66768, 3881)

In [8]:
df2 = pd.DataFrame([col_labels, FIELD_DESCRIPTION, TYPE, SUBTYPE], columns=col_labels)
main_df2 = pd.concat([df2, main_df2])

main_df2.columns=pd.MultiIndex.from_arrays(main_df2.iloc[0:4].values)
main_df2 = main_df2.iloc[4:]

main_df2.head()

                          RPT_REC_NUM                             PRVDR_NUM  \
                 Report Record Number             Hospital Provider Number
  HOSPITAL IDENTIFICATION INFORMATION   HOSPITAL IDENTIFICATION INFORMATION
   Report Record Number (RPT_REC_NUM) Hospital Provider Number  (PRVDR_NUM)
0                            717629.0                                344028
1                            717969.0                                180078
2                            719460.0                                520210
3                            719475.0                                063037
4                            719578.0                                171382

                               FI_NUM                         RPT_STUS_CD  \
           Fiscal Intermediary Number                  Report Status Code
  HOSPITAL IDENTIFICATION INFORMATION HOSPITAL IDENTIFICATION INFORMATION
  Fiscal Intermediary Number (FI_NUM)    Report Status Code (RPT_STUS_CD)
0                               11501                                   2
1                               05901                                   1
2                               06001                                   1
3                               04011                                   1
4                               05001                                   1

                                        FI_CREAT_DT  \
                Fiscal Intermediary/MAC Create Date
                HOSPITAL IDENTIFICATION INFORMATION
  Fiscal Intermediary/MAC Create Date (FI_CREAT_DT)
0                               2022-05-18 00:00:00
1                               2022-05-25 00:00:00
2                               2022-06-14 00:00:00
3                               2022-06-17 00:00:00
4                               2022-06-17 00:00:00

                            FY_BGN_DT                           FY_END_DT  \
              Fiscal Year Begin Date                Fiscal Year End Date
  HOSPITAL IDENTIFICATION INFORMATION HOSPITAL IDENTIFICATION INFORMATION
  Fiscal Year Begin Date  (FY_BGN_DT)   Fiscal Year End Date  (FY_END_DT)
0                 2022-01-01 00:00:00                 2022-01-31 00:00:00
1                 2021-10-01 00:00:00                 2021-11-30 00:00:00
2                 2021-10-01 00:00:00                 2021-12-31 00:00:00
3                 2021-10-08 00:00:00                 2021-12-31 00:00:00
4                 2021-10-01 00:00:00                 2021-12-31 00:00:00

                             UTIL_CODE                         TRNSMTL_NUM  \
              Utilization Code (L/N/F)                    NOT IN THIS FILE
   HOSPITAL IDENTIFICATION INFORMATION HOSPITAL IDENTIFICATION INFORMATION
  Utilization Code (L/N/F) (UTIL_CODE)      NOT IN THIS FILE (TRNSMTL_NUM)
0                                    N                                   O
1                                    F                                   O
2                                    F                                   O
3                                    F                                   O
4                                    F                                   O

                                STATE                           ST_CTY_CD  \
                       SSA State Code               SSA State County Code
  HOSPITAL IDENTIFICATION INFORMATION HOSPITAL IDENTIFICATION INFORMATION
               SSA State Code (STATE)   SSA State County Code (ST_CTY_CD)
0                                 NaN                                 NaN
1                                  18                               18570
2                                 NaN                                 NaN
3                                 NaN                                 NaN
4                                  17                               17020

                               CENSUS                              REGION  \
                 Census Division Code                     CMS Region Code
  HOSPITAL IDENTIFICATION INFORMATION HOSPITAL IDENTIFICATION INFORMATION
        Census Division Code (CENSUS)            CMS Region Code (REGION)
0                                 NaN                                 NaN
1                                 6.0                                 4.0
2                                 NaN                                 NaN
3                                 NaN                                 NaN
4                                 4.0                                 7.0

                                  MSA  \
                       Geographic MSA
  HOSPITAL IDENTIFICATION INFORMATION
                 Geographic MSA (MSA)
0                                 NaN
1                                 NaN
2                                 NaN
3                                 NaN
4                                 NaN

                                    A7_1_C2_1  \
                                        Land
  ANALYSIS OF CHANGES IN NEW CAPITAL BALANCES
       Column 2 (Purchases) Land  (A7_1_C2_1)
0                                         NaN
1                                         NaN
2                                         NaN
3                                         NaN
4                                         NaN

                                    A7_1_C3_1  \
                                        Land
  ANALYSIS OF CHANGES IN NEW CAPITAL BALANCES
       Column 3 (Donations) Land  (A7_1_C3_1)
0                                         NaN
1                                         NaN
2                                         NaN
3                                         NaN
4                                         NaN

                                   A7_1_C3_10  \
                                        Total
  ANALYSIS OF CHANGES IN NEW CAPITAL BALANCES
      Column 3 (Donations) Total (A7_1_C3_10)
0                                         NaN
1                                         NaN
2                                         NaN
3                                         NaN
4                                         NaN

                                           A7_1_C3_2  \
                                   Land Improvements
         ANALYSIS OF CHANGES IN NEW CAPITAL BALANCES
  Column 3 (Donations) Land Improvements (A7_1_C3_2)
0                                                NaN
1                                                NaN
2                                                NaN
3                                                NaN
4                                                NaN

                                                A7_1_C3_3  \
                                   Buildings and Fixtures
              ANALYSIS OF CHANGES IN NEW CAPITAL BALANCES
  Column 3 (Donations) Buildings and Fixtures (A7_1_C3_3)
0                                                NaN
1                                                NaN
2                                                NaN
3                                                NaN
4                                                NaN

                                               A7_1_C3_4  \
                                   Building Improvements
             ANALYSIS OF CHANGES IN NEW CAPITAL BALANCES
  Column 3 (Donations) Building Improvements (A7_1_C3_4)
0                                                NaN
1                                                NaN
2                                                NaN
3                                                NaN
4                                                NaN

                                         A7_1_C3_5  \
                                   Fixed Equipment
       ANALYSIS OF CHANGES IN NEW CAPITAL BALANCES
  Column 3 (Donations) Fixed Equipment (A7_1_C3_5)
0                                              NaN
1                                              NaN
2                                              NaN
3                                              NaN
4                                              NaN

                                           A7_1_C3_6  \
                                   Movable Equipment
         ANALYSIS OF CHANGES IN NEW CAPITAL BALANCES
  Column 3 (Donations) Movable Equipment (A7_1_C3_6)
0                                                NaN
1                                                NaN
2                                                NaN
3                                                NaN
4                                                NaN

                                                  A7_1_C3_7  \
                                                  Donations
                ANALYSIS OF CHANGES IN NEW CAPITAL BALANCES
  Column 7 (Fully Depreciated Assets) Donations (A7_1_C3_7)
0                                                NaN
1                                                NaN
2                                                NaN
3                                                NaN
4                                                NaN

                                    A7_1_C3_8  \
                                     Subtotal
  ANALYSIS OF CHANGES IN NEW CAPITAL BALANCES
    Column 3 (Donations) Subtotal (A7_1_C3_8)
0                                         NaN
1                                         NaN
2                                         NaN
3                                         NaN
4                                         NaN

                                               A7_1_C5_1  \
                                                   Land
             ANALYSIS OF CHANGES IN NEW CAPITAL BALANCES
  Column 5 (Disposals and Retirements) Land  (A7_1_C5_1)
0                                                NaN
1                                                NaN
2                                                NaN
3                                                NaN
4                                                NaN

                                                           A7_1_C5_2  \
                                                   Land Improvements
                         ANALYSIS OF CHANGES IN NEW CAPITAL BALANCES
  Column 5 (Disposals and Retirements) Land Improvements (A7_1_C5_2)
0                                                NaN
1                                                NaN
2                                                NaN
3                                                NaN
4                                                NaN

                                                                A7_1_C5_3  \
                                                   Buildings and Fixtures
                              ANALYSIS OF CHANGES IN NEW CAPITAL BALANCES
  Column 5 (Disposals and Retirements) Buildings and Fixtures (A7_1_C5_3)
0                                                NaN
1                                                NaN
2                                                NaN
3                                                NaN
4                                                NaN

                                                               A7_1_C5_4  \
                                                   Building Improvements
                             ANALYSIS OF CHANGES IN NEW CAPITAL BALANCES
  Column 5 (Disposals and Retirements) Building Improvements (A7_1_C5_4)
0                                                NaN
1                                                NaN
2                                                NaN
3                                                NaN
4                                                NaN

                                                         A7_1_C5_5  \
                                                   Fixed Equipment
                       ANALYSIS OF CHANGES IN NEW CAPITAL BALANCES
  Column 5 (Disposals and Retirements) Fixed Equipment (A7_1_C5_5)
0                                                NaN
1                                                NaN
2                                                NaN
3                                                NaN
4                                                NaN

                                                             A7_1_C5_7  \
                                                  Disp. And Retirement
                           ANALYSIS OF CHANGES IN NEW CAPITAL BALANCES
  Column 7 (Fully Depreciated Assets) Disp. And Retirement (A7_1_C5_7)
0                                                NaN
1                                                NaN
2                                                NaN
3                                                NaN
4                                                NaN

                                               A7_1_C7_1  \
                                                   Land
             ANALYSIS OF CHANGES IN NEW CAPITAL BALANCES
  Column 5 (Disposals and Retirements) Land  (A7_1_C7_1)
0                                                NaN
1                                                NaN
2                                                NaN
3                                                NaN
4                                                NaN

                                              A7_1_C7_10  \
                                                   Total
             ANALYSIS OF CHANGES IN NEW CAPITAL BALANCES
  Column 7 (Fully Depreciated Assets) Total (A7_1_C7_10)
0                                                NaN
1                                                NaN
2                                                NaN
3                                                NaN
4                                                NaN

                                                           A7_1_C7_2  \
                                                   Land Improvements
                         ANALYSIS OF CHANGES IN NEW CAPITAL BALANCES
  Column 5 (Disposals and Retirements) Land Improvements (A7_1_C7_2)
0                                                NaN
1                                                NaN
2                                                NaN
3                                                NaN
4                                                NaN

                                                                A7_1_C7_3  \
                                                   Buildings and Fixtures
                              ANALYSIS OF CHANGES IN NEW CAPITAL BALANCES
  Column 5 (Disposals and Retirements) Buildings and Fixtures (A7_1_C7_3)
0                                                NaN
1                                                NaN
2                                                NaN
3                                                NaN
4                                                NaN

                                                               A7_1_C7_4  \
                                                   Building Improvements
                             ANALYSIS OF CHANGES IN NEW CAPITAL BALANCES
  Column 5 (Disposals and Retirements) Building Improvements (A7_1_C7_4)
0                                                NaN
1                                                NaN
2                                                NaN
3                                                NaN
4                                                NaN

                                                         A7_1_C7_5  \
                                                   Fixed Equipment
                       ANALYSIS OF CHANGES IN NEW CAPITAL BALANCES
  Column 5 (Disposals and Retirements) Fixed Equipment (A7_1_C7_5)
0                                                NaN
1                                                NaN
2                                                NaN
3                                                NaN
4                                                NaN

                                                           A7_1_C7_6  \
                                                   Movable Equipment
                         ANALYSIS OF CHANGES IN NEW CAPITAL BALANCES
  Column 5 (Disposals and Retirements) Movable Equipment (A7_1_C7_6)
0                                                NaN
1                                                NaN
2                                                NaN
3                                                NaN
4                                                NaN

                                               A7_1_C7_7  \
                                                  Assets
             ANALYSIS OF CHANGES IN NEW CAPITAL BALANCES
  Column 7 (Fully Depreciated Assets) Assets (A7_1_C7_7)
0                                                NaN
1                                                NaN
2                                                NaN
3                                                NaN
4                                                NaN

                                                 A7_1_C7_8  \
                                                  Subtotal
               ANALYSIS OF CHANGES IN NEW CAPITAL BALANCES
  Column 7 (Fully Depreciated Assets) Subtotal (A7_1_C7_8)
0                                                NaN
1                                                NaN
2                                                NaN
3                                                NaN
4                                                NaN

                                                 A7_3_C7_3  \
                                                     Total
                    RECONCILIATION OF CAPITAL COST CENTERS
  Column 7 (Other Capital Related Costs) Total (A7_3_C7_3)
0                                                NaN
1                                                NaN
2                                                NaN
3                                                NaN
4                                                NaN

                                A8_C2_11                             A8_C2_13  \
             Sale of scrap, waste, etc.             Laundry and Linen Service
                             ADJUSTMENTS                          ADJUSTMENTS
  Sale of scrap, waste, etc.  (A8_C2_11) Laundry and Linen Service (A8_C2_13)
0                                    NaN                                  NaN
1                                    NaN                                  NaN
2                                    NaN                                  NaN
3                                    NaN                                  NaN
4                                    NaN                                  NaN

                                            A8_C2_15  \
             Rental of quarters to employee and oths
                                         ADJUSTMENTS
  Rental of quarters to employee and oths (A8_C2_15)
0                                                NaN
1                                                NaN
2                                                NaN
3                                                NaN
4                                                NaN

                                              A8_C2_16  \
             Sale of medical and surgical supplies to
                                           ADJUSTMENTS
  Sale of medical and surgical supplies to  (A8_C2_16)
0                                                NaN
1                                                NaN
2                                                NaN
3                                                NaN
4                                                NaN

                                         A8_C2_17  \
             Sale of drugs to other than patients
                                      ADJUSTMENTS
  Sale of drugs to other than patients (A8_C2_17)
0                                             NaN
1                                             NaN

In [9]:
CMS_Gen_Info_df = pd.read_csv('~/GitHub/HCRIS-databuilder/GeoData/Hospital_General_Information.tsv', sep='\t')
print(list(CMS_Gen_Info_df))
CMS_Gen_Info_df.head(10)

['Facility ID', 'Facility Name', 'Address', 'City', 'State', 'ZIP Code', 'County Name', 'Phone Number', 'Hospital Type', 'Hospital Ownership', 'Emergency Services', 'Meets criteria for promoting interoperability of EHRs', 'Hospital overall rating', 'Hospital overall rating footnote', 'Mortality national comparison', 'Mortality national comparison footnote', 'Safety of care national comparison', 'Safety of care national comparison footnote', 'Readmission national comparison', 'Readmission national comparison footnote', 'Patient experience national comparison', 'Patient experience national comparison footnote', 'Effectiveness of care national comparison', 'Effectiveness of care national comparison footnote', 'Timeliness of care national comparison', 'Timeliness of care national comparison footnote', 'Efficient use of medical imaging national comparison', 'Efficient use of medical imaging national comparison footnote', 'Location']

,Facility ID,Facility Name,Address,City,State,ZIP Code,County Name,Phone Number,Hospital Type,Hospital Ownership,Emergency Services,Meets criteria for promoting interoperability of EHRs,Hospital overall rating,Hospital overall rating footnote,Mortality national comparison,Mortality national comparison footnote,Safety of care national comparison,Safety of care national comparison footnote,Readmission national comparison,Readmission national comparison footnote,Patient experience national comparison,Patient experience national comparison footnote,Effectiveness of care national comparison,Effectiveness of care national comparison footnote,Timeliness of care national comparison,Timeliness of care national comparison footnote,Efficient use of medical imaging national comparison,Efficient use of medical imaging national comparison footnote,Location
0,030084,CHINLE COMPREHENSIVE HEALTH CARE FACILITY,"US HWY 191, HOSPITAL ROAD",CHINLE,AZ,86503,APACHE,(928) 674-7001,Acute Care Hospitals,Government - Federal,True,True,4,17.0,Not Available,5.0,Not Available,5.0,Above the national average,NaN,Same as the national average,NaN,Below the national average,NaN,Not Available,5.0,Not Available,16.0,NaN
1,044022,CONWAY BEHAVIORAL HEALTH,2255 STURGIS ROAD,CONWAY,AR,72034,FAULKNER,(501) 205-0011,Psychiatric,Proprietary,False,NaN,Not Available,19.0,Not Available,19.0,Not Available,19.0,Not Available,19.0,Not Available,19.0,Not Available,19.0,Not Available,19.0,Not Available,19.0,NaN
2,10021F,96th Medical Group (Eglin AFB),96 MDG 307 Boatner Rd Suite 114,Eglin AFB,FL,32542,OKALOOSA,(850) 883-8600,Acute Care - Department of Defense,Department of Defense,True,NaN,Not Available,22.0,Not Available,22.0,Not Available,22.0,Not Available,22.0,Not Available,22.0,Not Available,22.0,Not Available,22.0,Not Available,22.0,NaN
3,170204,"ROCK REGIONAL HOSPITAL, LLC",3251 NORTH ROCK ROAD,DERBY,KS,67037,SEDGWICK,(833) 345-7625,Acute Care Hospitals,Proprietary,True,NaN,Not Available,5.0,Not Available,5.0,Not Available,5.0,Not Available,5.0,Not Available,5.0,Not Available,5.0,Not Available,5.0,Not Available,5.0,POINT (-97.244407 37.582147)
4,171322,HAMILTON COUNTY HOSPITAL,700 NORTH HUSER,SYRACUSE,KS,67878,HAMILTON,(620) 384-7461,Critical Access Hospitals,Government - Local,True,NaN,Not Available,16.0,Not Available,16.0,Not Available,16.0,Not Available,16.0,Not Available,16.0,Not Available,5.0,Same as the national average,NaN,Not Available,16.0,NaN
5,174020,COTTONWOOD SPRINGS LLC,13351 S ARAPAHO DRIVE,OLATHE,KS,66062,JOHNSON,(913) 353-3000,Psychiatric,Proprietary,False,NaN,Not Available,19.0,Not Available,19.0,Not Available,19.0,Not Available,19.0,Not Available,19.0,Not Available,19.0,Not Available,19.0,Not Available,19.0,POINT (-94.768837 38.885884)
6,181304,TRIGG COUNTY HOSPITAL,254 MAIN STREET,CADIZ,KY,42211,TRIGG,(270) 522-3215,Critical Access Hospitals,Voluntary non-profit - Private,True,NaN,Not Available,16.0,Not Available,5.0,Not Available,16.0,Not Available,5.0,Not Available,16.0,Not Available,5.0,Same as the national average,NaN,Not Available,5.0,POINT (-87.821288 36.867247)
7,190160,GLENWOOD REGIONAL MEDICAL CENTER,503 MCMILLAN ROAD,WEST MONROE,LA,71291,OUACHITA,(318) 329-4600,Acute Care Hospitals,Proprietary,True,True,2,NaN,Above the national average,NaN,Above the national average,NaN,Below the national average,NaN,Below the national average,NaN,Same as the national average,NaN,Same as the national average,NaN,Below the national average,NaN,POINT (-92.156761 32.513462)
8,214002,EASTERN SHORE HOSPITAL CENTER,POST OFFICE BOX 800,CAMBRIDGE,MD,21613,DORCHESTER,(410) 221-2525,Psychiatric,Government - State,False,NaN,Not Available,19.0,Not Available,19.0,Not Available,19.0,Not Available,19.0,Not Available,19.0,Not Available,19.0,Not Available,19.0,Not Available,19.0,NaN
9,231314,MCKENZIE HEALTH SYSTEM,120 N DELAWARE STREET,SANDUSKY,MI,48471,SANILAC,(810) 648-3770,Critical Access Hospitals,Voluntary non-profit - Private,True,True,Not Available,16.0,Not Available,5.0,Not Available,16.0,Not Available,5.0,Not Available,16.0,Not Available,5.0,Not Available,5.0,Not Available,5.0,POINT (-82.832937 43.423426)

In [10]:
hospital_ls = main_df2.iloc[:, (main_df2.columns.get_level_values(0) == 'S2_1_C1_3')].T.values.tolist()[0]
id_ls = main_df2.iloc[:, (main_df2.columns.get_level_values(0) == 'PRVDR_NUM')].T.values.tolist()[0]

print(hospital_ls[0:4])
print(id_ls[0:4])

['STRATEGIC BEHAVIORAL CENTER - GARNER', 'PAUL B. HALL REGIONAL MEDICAL CENTER', 'MARSHFIELD MEDICAL CENTER-EAU CLAIRE', 'COBALT REHAB HOSP WESTMINSTER']
['344028', '180078', '520210', '063037']

In [11]:
lats = []
lons = []
Htypes = []
Ctypes = []

misses = 0
hits = 0
for i, h in enumerate(hospital_ls):
    
    #if i > 100: break   
    fid = id_ls[i]
    
    try:
        df = CMS_Gen_Info_df[CMS_Gen_Info_df['Facility ID'] == fid]
            
        loc = df['Location'].iloc[0]
        loc = loc.replace("POINT (","") 
        loc = loc.replace(")","")
        loc = loc.split(" ")
            
        lat = loc[1]
        lon = loc[0]
        lats.append(lat)
        lons.append(lon)
        
        htype = df['Hospital Type'].iloc[0]
        Htypes.append(htype)
        ctype = df['Hospital Ownership'].iloc[0]
        Ctypes.append(ctype)
        
        #hits += 1
        
    except:
        #misses += 1
        lats.append(float('NaN'))
        lons.append(float('NaN'))
        Htypes.append(float('NaN'))
        Ctypes.append(float('NaN'))

In [12]:
for i, val in enumerate(lats):
    if pd.isnull(val): 
        continue
    else:
        print(val, lons[i], Htypes[i], Ctypes[i])
    if i > 10:
        break

35.680334 -78.560684 Psychiatric Proprietary
37.815015 -82.812803 Acute Care Hospitals Proprietary
44.793318 -91.519083 Acute Care Hospitals Voluntary non-profit - Private
35.746554 -89.548949 Critical Access Hospitals Proprietary
34.004403 -81.114361 Acute Care Hospitals Government - Hospital District or Authority
31.374382 -84.946245 Critical Access Hospitals Voluntary non-profit - Private
38.823541 -81.728325 Critical Access Hospitals Voluntary non-profit - Other
45.508042 -91.759027 Acute Care Hospitals Voluntary non-profit - Private

In [13]:
main_df2[('Lat', 'Lat', 'Lat', 'Lat')] = lats
main_df2[('Lon', 'Lon', 'Lon', 'Lon')] = lons
main_df2[('Control type, text', 'Control type, text', 'Control type, text', 'Control type, text')] = Ctypes
main_df2[('Hospital type, text', 'Hospital type, text', 'Hospital type, text', 'Hospital type, text')] = Htypes
main_df2[('Num and Name', 'Num and Name', 'Num and Name', 'Num and Name')] = main_df2[('S2_1_C1_3', 'Hospital Name ', 'No Description', 'Hospital Name  (S2_1_C1_3)')] +' (' + main_df2[('PRVDR_NUM', 'Hospital Provider Number ', 'HOSPITAL IDENTIFICATION INFORMATION', 'Hospital Provider Number  (PRVDR_NUM)')] + ')'

In [14]:
badnames = ['20994', float('NaN'), '-0007', '1', '330354', '4499 ACUSHNET AVENUE OPERATING COMPA',
           '4499 ACUSHNET AVENUE OPERATING COMPM']

main_df2 = main_df2[~main_df2[('S2_1_C1_3', 'Hospital Name ', 'No Description', 'Hospital Name  (S2_1_C1_3)')].isin(badnames)]

In [15]:
tdf = main_df2.filter(items=[('Lat', 'Lat', 'Lat', 'Lat'),
                             ('Lon', 'Lon', 'Lon', 'Lon'),
                             ('Control type, text', 'Control type, text', 'Control type, text', 'Control type, text'),
                             ('Hospital type, text', 'Hospital type, text', 'Hospital type, text', 'Hospital type, text'),
                             ('Num and Name', 'Num and Name', 'Num and Name', 'Num and Name'),
                             ('S3_1_C2_27', 'Total Facility', 'NUMBER OF BEDS', 'Total Facility (S3_1_C2_27)'),
                             ('S2_1_C2_2', 'Hospital State', 'No Description', 'Hospital State (S2_1_C2_2)'),
                            ], axis=1)

tdf.to_pickle('GenDat4App/GenDat4App.pkl', protocol=4)

In [16]:
main_df2[('FY_END_DT', 'Fiscal Year End Date ', 'HOSPITAL IDENTIFICATION INFORMATION', 'Fiscal Year End Date  (FY_END_DT)')] = pd.to_datetime(main_df2[('FY_END_DT', 'Fiscal Year End Date ', 'HOSPITAL IDENTIFICATION INFORMATION', 'Fiscal Year End Date  (FY_END_DT)')])
main_df2 = main_df2.sort_values(by=[('Num and Name', 'Num and Name', 'Num and Name', 'Num and Name'),
                     ('FY_END_DT', 'Fiscal Year End Date ', 'HOSPITAL IDENTIFICATION INFORMATION', 'Fiscal Year End Date  (FY_END_DT)')],
                     ascending=[True, True])

In [17]:
import re

numNname = sorted(list(set(main_df2[('Num and Name', 'Num and Name', 'Num and Name', 'Num and Name')].tolist())))

for i, val in enumerate(numNname):
    prvdr = re.sub('\ |\?|\.|\!|\/|\;|\:', '', val)

    tdf = main_df2[main_df2[('Num and Name', 'Num and Name', 'Num and Name', 'Num and Name')] == val]
    tdf.to_csv('provider_data/' + prvdr + '.csv')

In [19]:
main_df2.to_pickle('all_data/HCRIS.pkl')

In [20]:

report_categories = list(set(main_df2.columns.get_level_values(2).tolist()))
report_categories = [x for x in report_categories if str(x) != 'nan']
report_categories = [x for x in report_categories if str(x) != 'Lat']
report_categories = [x for x in report_categories if str(x) != 'Lon']
report_categories = [x for x in report_categories if str(x) != 'Num and Name']
report_categories = [x for x in report_categories if str(x) != 'Hospital type, text']
#report_categories = [x for x in report_categories if str(x) != '']
report_categories = [x for x in report_categories if str(x) != 'HOSPITAL IDENTIFICATION INFORMATION']

report_categories = [x for x in report_categories if str(x) != 'Control type, text']
report_categories = [x for x in report_categories if str(x) != 'HOSPITAL IDENTIFICATION INFORMATION']
report_categories = [x for x in report_categories if str(x) != 'HOSPITAL IDENTIFICATION INFORMATION']
report_categories.sort()

import csv

with open('GenDat4App/report_categories.csv', 'w+', newline='') as OUT:
    writer = csv.writer(OUT)
    writer.writerow(report_categories)
    
    
sub_categories = list(set(main_df2.columns.get_level_values(3).tolist()))
sub_categories.sort()

with open('GenDat4App/sub_categories.csv', 'w+', newline='') as OUT:
    writer = csv.writer(OUT)
    writer.writerow(sub_categories)