In [1]:
import pandas as pd
import warnings
from IPython.utils import io
import sys
warnings.filterwarnings('ignore')
pd.set_option('display.max_columns', None)
#pd.set_option('display.max_rows', None)

## **Load, format, and examine 'prds_hosp10_yr' sas7bdat files**
## Concatenate files into a single dataframe (main_df) and join with the crosswalk file

In [2]:
with io.capture_output() as captured: prds_2010_df = pd.read_sas('~/GitHub/HCRIS-databuilder/hosp10-sas/prds_hosp10_yr2010.sas7bdat')
prds_2010_df['File Date'] = ['2010'] * prds_2010_df.shape[0]
print('prds_hosp10_yr2010: (rows, columns) =', prds_2010_df.shape)

with io.capture_output() as captured: prds_2011_df = pd.read_sas('~/GitHub/HCRIS-databuilder/hosp10-sas/prds_hosp10_yr2011.sas7bdat')
prds_2011_df['File Date'] = ['2011'] * prds_2011_df.shape[0]
print('prds_hosp10_yr2011: (rows, columns) =', prds_2011_df.shape)

with io.capture_output() as captured: prds_2012_df = pd.read_sas('~/GitHub/HCRIS-databuilder/hosp10-sas/prds_hosp10_yr2012.sas7bdat')
prds_2012_df['File Date'] = ['2012'] * prds_2012_df.shape[0]
print('prds_hosp10_yr2012: (rows, columns) =', prds_2012_df.shape)

with io.capture_output() as captured: prds_2013_df = pd.read_sas('~/GitHub/HCRIS-databuilder/hosp10-sas/prds_hosp10_yr2013.sas7bdat')
prds_2013_df['File Date'] = ['2013'] * prds_2013_df.shape[0]
print('prds_hosp10_yr2013: (rows, columns) =', prds_2013_df.shape)

with io.capture_output() as captured: prds_2014_df = pd.read_sas('~/GitHub/HCRIS-databuilder/hosp10-sas/prds_hosp10_yr2014.sas7bdat')
prds_2014_df['File Date'] = ['2014'] * prds_2014_df.shape[0]
print('prds_hosp10_yr2014: (rows, columns) =', prds_2014_df.shape)

with io.capture_output() as captured: prds_2015_df = pd.read_sas('~/GitHub/HCRIS-databuilder/hosp10-sas/prds_hosp10_yr2015.sas7bdat')
prds_2015_df['File Date'] = ['2015'] * prds_2015_df.shape[0]
print('prds_hosp10_yr2015: (rows, columns) =', prds_2015_df.shape)

with io.capture_output() as captured: prds_2016_df = pd.read_sas('~/GitHub/HCRIS-databuilder/hosp10-sas/prds_hosp10_yr2016.sas7bdat')
prds_2016_df['File Date'] = ['2016'] * prds_2016_df.shape[0]
print('prds_hosp10_yr2016: (rows, columns) =', prds_2016_df.shape)

with io.capture_output() as captured: prds_2017_df = pd.read_sas('~/GitHub/HCRIS-databuilder/hosp10-sas/prds_hosp10_yr2017.sas7bdat')
prds_2017_df['File Date'] = ['2017'] * prds_2017_df.shape[0]
print('prds_hosp10_yr2017: (rows, columns) =', prds_2017_df.shape)

with io.capture_output() as captured: prds_2018_df = pd.read_sas('~/GitHub/HCRIS-databuilder/hosp10-sas/prds_hosp10_yr2018.sas7bdat')
prds_2018_df['File Date'] = ['2018'] * prds_2018_df.shape[0]
print('prds_hosp10_yr2018: (rows, columns) =', prds_2018_df.shape)

with io.capture_output() as captured: prds_2019_df = pd.read_sas('~/GitHub/HCRIS-databuilder/hosp10-sas/prds_hosp10_yr2019.sas7bdat')
prds_2019_df['File Date'] = ['2019'] * prds_2019_df.shape[0]
print('prds_hosp10_yr2019: (rows, columns) =', prds_2019_df.shape)

with io.capture_output() as captured: prds_2020_df = pd.read_sas('~/GitHub/HCRIS-databuilder/hosp10-sas/prds_hosp10_yr2020.sas7bdat')
prds_2020_df['File Date'] = ['2020'] * prds_2020_df.shape[0]
print('prds_hosp10_yr2020: (rows, columns) =', prds_2020_df.shape)

with io.capture_output() as captured: prds_2021_df = pd.read_sas('~/GitHub/HCRIS-databuilder/hosp10-sas/prds_hosp10_yr2021.sas7bdat')
prds_2021_df['File Date'] = ['2021'] * prds_2021_df.shape[0]
print('prds_hosp10_yr2021: (rows, columns) =', prds_2021_df.shape)

with io.capture_output() as captured: prds_2022_df = pd.read_sas('~/GitHub/HCRIS-databuilder/hosp10-sas/prds_hosp10_yr2022.sas7bdat')
prds_2022_df['File Date'] = ['2022'] * prds_2022_df.shape[0]
print('prds_hosp10_yr2022: (rows, columns) =', prds_2022_df.shape)

prds_hosp10_yr2010: (rows, columns) = (2323, 5522)
prds_hosp10_yr2011: (rows, columns) = (6150, 5522)
prds_hosp10_yr2012: (rows, columns) = (6227, 5522)
prds_hosp10_yr2013: (rows, columns) = (6248, 5522)
prds_hosp10_yr2014: (rows, columns) = (6250, 5522)
prds_hosp10_yr2015: (rows, columns) = (6257, 5522)
prds_hosp10_yr2016: (rows, columns) = (6211, 5522)
prds_hosp10_yr2017: (rows, columns) = (6173, 5522)
prds_hosp10_yr2018: (rows, columns) = (6159, 5522)
prds_hosp10_yr2019: (rows, columns) = (6118, 5522)
prds_hosp10_yr2020: (rows, columns) = (6050, 5522)
prds_hosp10_yr2021: (rows, columns) = (2597, 5522)
prds_hosp10_yr2022: (rows, columns) = (5, 5522)

In [3]:
main_df = pd.concat([prds_2021_df, prds_2020_df, prds_2019_df, prds_2018_df, prds_2017_df, prds_2016_df, 
                     prds_2015_df, prds_2014_df, prds_2013_df, prds_2012_df, prds_2011_df, prds_2010_df,
                     ], ignore_index=True)

main_df = main_df.applymap(lambda x: x.decode() if isinstance(x, bytes) else x)
main_df = main_df.dropna(axis=1, how='all')
main_df.head()

   rpt_rec_num prvdr_num fi_num rpt_stus_cd fi_creat_dt  fy_bgn_dt  fy_end_dt  \
0     692984.0    441314  10001           1  2021-06-24 2020-10-01 2020-12-31
1     693446.0    420073  11001           1  2021-07-01 2020-10-01 2021-01-31
2     695160.0    353026  03001           2  2021-08-06 2020-10-01 2020-12-31
3     695329.0    111314  10001           1  2021-08-09 2020-10-01 2020-12-31
4     695374.0    341317  11501           1  2021-08-10 2020-10-01 2020-12-31

  util_cd trnsmtl_num state st_cty_cd  census  region    proc_dt   msa  \
0       F           N    44     44480     6.0     4.0 2021-06-25   NaN
1       F           N    42     42310     5.0     4.0 2021-07-15  1760
2       F           N   NaN       NaN     NaN     NaN 2021-08-09   NaN
3       F           N    11     11410     5.0     4.0 2021-08-11   NaN
4       F           N    34     34840     5.0     4.0 2021-08-11  3120

   A_C1_114  A_C1_4201  A_C1_4501  A_C2_114  A_C2_4201  A_C2_4501  A_C2_61  \
0       NaN        NaN        NaN       NaN        NaN        NaN      NaN
1       NaN        NaN        NaN       NaN        NaN        NaN      NaN
2       NaN        NaN        NaN       NaN        NaN        NaN      NaN
3       NaN        NaN        NaN       NaN        NaN        NaN      NaN
4       NaN        NaN        NaN       NaN        NaN        NaN      NaN

   A_C6_4201  A_C6_4501  A_C6_61  B_1_C0_4201  B_1_C0_4501  B_1_C0_61  \
0        NaN        NaN      NaN          NaN          NaN        NaN
1        NaN        NaN      NaN          NaN          NaN        NaN
2        NaN        NaN      NaN          NaN          NaN        NaN
3        NaN        NaN      NaN          NaN          NaN        NaN
4        NaN        NaN      NaN          NaN          NaN        NaN

   B_1_C21_109  B_1_C21_42  B_1_C21_45  B_1_C21_46  B_1_C21_94  B_1_C22_109  \
0          NaN         NaN         NaN         NaN         NaN          NaN
1          NaN         NaN         NaN         NaN         NaN          NaN
2          NaN         NaN         NaN         NaN         NaN          NaN
3          NaN         NaN         NaN         NaN         NaN          NaN
4          NaN         NaN         NaN         NaN         NaN          NaN

   B_1_C22_110  B_1_C22_111  B_1_C22_42  B_1_C22_45  B_1_C22_46  B_1_C22_94  \
0          NaN          NaN         NaN         NaN         NaN         NaN
1          NaN          NaN         NaN         NaN         NaN         NaN
2          NaN          NaN         NaN         NaN         NaN         NaN
3          NaN          NaN         NaN         NaN         NaN         NaN
4          NaN          NaN         NaN         NaN         NaN         NaN

   B_1_C26_4201  B_1_C26_4501  B_1_C26_61  B_2_C26_4201  B_2_C26_4501  \
0           NaN           NaN         NaN           NaN           NaN
1           NaN           NaN         NaN           NaN           NaN
2           NaN           NaN         NaN           NaN           NaN
3           NaN           NaN         NaN           NaN           NaN
4           NaN           NaN         NaN           NaN           NaN

   C_1_C5_4201  C_1_C5_4501  C_1_C5_61  C_1_C6_100  C_1_C6_111  C_1_C6_4201  \
0          NaN          NaN        NaN         NaN         NaN          NaN
1          NaN          NaN        NaN         NaN         NaN          NaN
2          NaN          NaN        NaN         NaN         NaN          NaN
3          NaN          NaN        NaN         NaN         NaN          NaN
4          NaN          NaN        NaN         NaN         NaN          NaN

   C_1_C6_4501  C_1_C6_61  C_1_C7_111  D3_HOS_C2_201  D3_HOS_C2_43  \
0          NaN        NaN         NaN            NaN           NaN
1          NaN        NaN         NaN            NaN           NaN
2          NaN        NaN         NaN            NaN           NaN
3          NaN        NaN         NaN            NaN           NaN
4          NaN        NaN         NaN            NaN           NaN

   D3_HOS_C2_61  D3_HOS_C3_61  D3_IPF_C2_41  D3_IPF_C2_42  D3_IPF_C2_94  \
0           NaN           NaN           NaN           NaN           NaN
1           NaN           NaN           NaN           NaN           NaN
2           NaN           NaN           NaN           NaN           NaN
3           NaN           NaN           NaN           NaN           NaN
4           NaN           NaN           NaN           NaN           NaN

   D3_IPF_C3_94  D3_IRF_C2_61  D3_IRF_C3_61  D3_SNF_C2_30  D3_SNF_C2_41  \
0           NaN           NaN           NaN           NaN           NaN
1           NaN           NaN           NaN           NaN           NaN
2           NaN           NaN           NaN           NaN           NaN
3           NaN           NaN           NaN           NaN           NaN
4           NaN           NaN           NaN           NaN           NaN

   D3_SNF_C2_94  D3_SNF_C3_94  D_1_HOS_C4_4201  D_2_IPF_C5_94  D_4_HOS_C11_94  \
0           NaN           NaN              NaN            NaN             NaN
1           NaN           NaN              NaN            NaN             NaN
2           NaN           NaN              NaN            NaN             NaN
3           NaN           NaN              NaN            NaN             NaN
4           NaN           NaN              NaN            NaN             NaN

   D_4_HOS_C12_94  D_4_HOS_C2_94  D_4_HOS_C3_94  D_4_IRF_C13_74  \
0             NaN            NaN            NaN             NaN
1             NaN            NaN            NaN             NaN
2             NaN            NaN            NaN             NaN
3             NaN            NaN            NaN             NaN
4             NaN            NaN            NaN             NaN

   D_4_SNF_C11_74  D_4_SNF_C13_200  D_5_HOS_C2_94  D_5_HOS_C3_61  \
0             NaN              NaN            NaN            NaN
1             NaN              NaN            NaN            NaN
2             NaN              NaN            NaN            NaN
3             NaN              NaN            NaN            NaN
4             NaN              NaN            NaN            NaN

   D_5_HOS_C6_61  E1_2_HOS_C1_30  E1_2_HOS_C1_31  E1_2_HOS_C1_6  \
0            NaN             NaN             NaN            NaN
1            NaN             NaN             NaN            NaN
2            NaN             NaN             NaN            NaN
3            NaN             NaN             NaN            NaN
4            NaN             NaN             NaN            NaN

   E1_2_HOS_C1_7  E2_SWSNF_C1_7  E3_1_HOS_C1_20  E3_2_HOS_C1_13  \
0            NaN            NaN             NaN             NaN
1            NaN            NaN             NaN             NaN
2            NaN            NaN             NaN             NaN
3            NaN            NaN             NaN             NaN
4            NaN            NaN             NaN             NaN

   E3_2_HOS_C1_29  E3_2_HOS_C1_3101  E3_2_IPF_C1_13  E3_2_IPF_C1_15  \
0             NaN               NaN             NaN             NaN
1             NaN               NaN             NaN             NaN
2             NaN               NaN             NaN             NaN
3             NaN               NaN             NaN             NaN
4             NaN               NaN             NaN             NaN

   E3_2_IPF_C1_29  E3_2_IPF_C1_3101  E3_2_IPF_C1_33  E3_3_HOS_C1_16  \
0             NaN               NaN             NaN             NaN
1             NaN               NaN             NaN             NaN
2             NaN               NaN             NaN             NaN
3             NaN               NaN             NaN             NaN
4             NaN               NaN             NaN             NaN

   E3_3_HOS_C1_30  E3_3_HOS_C1_3201  E3_3_HOS_C1_51  E3_3_HOS_C1_52  \
0             NaN               NaN             NaN             NaN
1             NaN               NaN             NaN             NaN
2             NaN               NaN             NaN             NaN
3             NaN               NaN             NaN             NaN
4             NaN               NaN             NaN             NaN

   E3_3_HOS_C1_53  E3_3_IRF_C1_14  E3_3_IRF_C1_16  E3_3_IRF_C1_30  \
0             NaN             NaN             NaN             NaN
1             NaN             NaN             NaN             NaN
2             NaN             NaN             NaN             NaN
3             NaN             NaN             NaN             NaN
4             NaN             NaN             NaN             NaN

   E3_3_IRF_C1_3201  E3_3_IRF_C1_34  E3_3_IRF_C1_51  E3_3_IRF_C1_52  \
0               NaN             NaN             NaN             NaN
1               NaN             NaN             NaN             NaN
2               NaN             NaN             NaN             NaN
3               NaN             NaN             NaN             NaN
4               NaN             NaN             NaN             NaN

   E3_3_IRF_C1_53  E3_4_HOS_C1_19  E3_4_HOS_C1_20  E3_4_HOS_C1_2201  \
0             NaN             NaN             NaN               NaN
1             NaN             NaN             NaN               NaN
2             NaN             NaN             NaN               NaN
3             NaN             NaN             NaN               NaN
4             NaN             NaN             NaN               NaN

   E3_4_HOS_C1_4  E3_4_HOS_C1_51  E3_4_HOS_C1_52  E3_4_HOS_C1_53  \
0            NaN             NaN             NaN             NaN
1            NaN             NaN             NaN             NaN
2            NaN             NaN             NaN             NaN
3            NaN             NaN             NaN             NaN
4            NaN             NaN             NaN             NaN

   E3_4_HOS_C1_6  E3_5_C1_15  E3_5_C1_2  E3_5_C1_7  E3_6_SNF_C1_17  \
0            NaN         NaN        NaN        NaN             NaN
1            NaN         NaN        NaN        NaN             NaN
2            NaN         NaN        NaN        NaN             NaN
3            NaN         NaN        NaN        NaN             NaN
4            NaN         NaN        NaN        NaN             NaN

   E_A_HOS_C101_1  E_A_HOS_C101_2  E_A_HOS_C101_202  E_A_HOS_C101_48  \
0             NaN             NaN               NaN              NaN
1             NaN             NaN               NaN              NaN
2             NaN             NaN               NaN              NaN
3             NaN             NaN               NaN              NaN
4             NaN             NaN               NaN              NaN

   E_A_HOS_C1_1  E_A_HOS_C1_2  E_A_HOS_C1_202  E_A_HOS_C1_51  E_A_HOS_C1_56  \
0           NaN           NaN             NaN            NaN            NaN
1           NaN           NaN             NaN            NaN            NaN
2           NaN           NaN             NaN            NaN            NaN
3           NaN           NaN             NaN            NaN            NaN
4           NaN           NaN             NaN            NaN            NaN

   E_A_HOS_C1_69  E_A_HOS_C1_7089  E_A_HOS_C1_7101  E_A_HOS_C1_93  \
0            NaN              NaN              NaN            NaN
1            NaN              NaN              NaN            NaN
2            NaN              NaN              NaN            NaN
3            NaN              NaN              NaN            NaN
4            NaN              NaN              NaN            NaN

   E_A_HOS_C1_94  E_A_HOS_C1_95  E_A_HOS_C1_96  E_B_HOS_C1_4001  \
0            NaN            NaN            NaN              NaN
1            NaN            NaN            NaN              NaN
2            NaN            NaN            NaN              NaN
3            NaN            NaN            NaN              NaN
4            NaN            NaN            NaN              NaN

   E_B_IPF_C1_15  E_B_IPF_C1_16  E_B_IPF_C1_17  E_B_IPF_C1_20  E_B_IPF_C1_23  \
0            NaN            NaN            NaN            NaN            NaN
1            NaN            NaN            NaN            NaN            NaN
2            NaN            NaN            NaN            NaN            NaN
3            NaN            NaN            NaN            NaN            NaN
4            NaN            NaN            NaN            NaN            NaN

   E_B_IPF_C1_4001  E_B_IPF_C1_42  E_B_IPF_C1_8  E_B_IRF_C1_15  E_B_IRF_C1_16  \
0              NaN            NaN           NaN            NaN            NaN
1              NaN            NaN           NaN            NaN            NaN
2              NaN            NaN           NaN            NaN            NaN
3              NaN            NaN           NaN            NaN            NaN
4              NaN            NaN           NaN            NaN            NaN

   E_B_IRF_C1_17  E_B_IRF_C1_20  E_B_IRF_C1_23  E_B_IRF_C1_31  E_B_IRF_C1_38  \
0            NaN            NaN            NaN            NaN            NaN
1            NaN            NaN            NaN            NaN            NaN
2            NaN            NaN            NaN            NaN            NaN
3            NaN            NaN            NaN            NaN            NaN
4            NaN            NaN            NaN            NaN            NaN

   E_B_IRF_C1_42  E_B_IRF_C1_8  E_B_SNF_C1_15  E_B_SNF_C1_16  E_B_SNF_C1_17  \
0            NaN           NaN            NaN            NaN            NaN
1            NaN           NaN            NaN            NaN            NaN
2            NaN           NaN            NaN            NaN            NaN
3            NaN           NaN            NaN            NaN            NaN
4            NaN           NaN            NaN            NaN            NaN

   E_B_SNF_C1_2  E_B_SNF_C1_24  E_B_SNF_C1_26  E_B_SNF_C1_31  E_B_SNF_C1_42  \
0           NaN            NaN            NaN            NaN            NaN
1           NaN            NaN            NaN            NaN            NaN
2           NaN            NaN            NaN            NaN            NaN
3           NaN            NaN            NaN            NaN            NaN
4           NaN            NaN            NaN            NaN            NaN

   E_B_SNF_C1_9  G2_C1_25  G2_C1_401  H3_1_HHA1_C6_3  H3_1_HHA2_C10_16  \
0           NaN       NaN        NaN             NaN               NaN
1           NaN       NaN        NaN             NaN               NaN
2           NaN       NaN        NaN             NaN               NaN
3           NaN       NaN        NaN             NaN               NaN
4           NaN       NaN        NaN             NaN               NaN

   H3_1_HHA2_C11_15  H3_1_HHA2_C6_1  H3_1_HHA2_C6_2  H3_1_HHA2_C6_3  \
0               NaN             NaN             NaN             NaN
1               NaN             NaN             NaN             NaN
2               NaN             NaN             NaN             NaN
3               NaN             NaN             NaN             NaN
4               NaN             NaN             NaN             NaN

   H3_1_HHA2_C6_4  H3_1_HHA2_C6_5  H3_1_HHA2_C6_6  H3_1_HHA2_C6_7  \
0             NaN             NaN             NaN             NaN
1             NaN             NaN             NaN             NaN
2             NaN             NaN             NaN             NaN
3             NaN             NaN             NaN             NaN
4             NaN             NaN             NaN             NaN

   H3_1_HHA2_C9_15  H3_1_HHA3_C10_15  H3_1_HHA3_C5_1  H3_1_HHA3_C5_2  \
0              NaN               NaN             NaN             NaN
1              NaN               NaN             NaN             NaN
2              NaN               NaN             NaN             NaN
3              NaN               NaN             NaN             NaN
4              NaN               NaN             NaN             NaN

   H3_1_HHA3_C5_3  H3_1_HHA3_C5_4  H3_1_HHA3_C5_5  H3_1_HHA3_C5_6  \
0             NaN             NaN             NaN             NaN
1             NaN             NaN             NaN             NaN
2             NaN             NaN             NaN             NaN
3             NaN             NaN             NaN             NaN
4             NaN             NaN             NaN             NaN

   H3_1_HHA3_C6_1  H3_1_HHA3_C6_2  H3_1_HHA3_C6_3  H3_1_HHA3_C6_4  \
0             NaN             NaN             NaN             NaN
1             NaN             NaN             NaN             NaN
2             NaN             NaN             NaN             NaN
3             NaN             NaN             NaN             NaN
4             NaN             NaN             NaN             NaN

   H3_1_HHA3_C6_5  H3_1_HHA3_C6_6  H3_1_HHA3_C6_7  H3_1_HHA3_C7_1  \
0             NaN             NaN             NaN             NaN
1             NaN             NaN             NaN             NaN
2             NaN             NaN             NaN             NaN
3             NaN             NaN             NaN             NaN
4             NaN             NaN             NaN             NaN

   H3_1_HHA3_C7_2  H3_1_HHA3_C7_3  H3_1_HHA3_C7_4  H3_1_HHA3_C7_5  \
0             NaN             NaN             NaN             NaN
1             NaN             NaN             NaN             NaN
2             NaN             NaN             NaN             NaN
3             NaN             NaN             NaN             NaN
4             NaN             NaN             NaN             NaN

   H3_1_HHA3_C7_6  H3_1_HHA3_C7_7  H3_1_HHA3_C9_15  H4_2_HHA1_C1_10  \
0             NaN             NaN              NaN              NaN
1             NaN             NaN              NaN              NaN
2             NaN             NaN              NaN              NaN
3             NaN             NaN              NaN              NaN
4             NaN             NaN              NaN              NaN

   H4_2_HHA1_C1_11  H4_2_HHA1_C1_12  H4_2_HHA1_C1_13  H4_2_HHA1_C1_14  \
0              NaN              NaN              NaN              NaN
1              NaN              NaN              NaN              NaN
2              NaN              NaN              NaN              NaN
3              NaN              NaN              NaN              NaN
4              NaN              NaN              NaN              NaN

   H4_2_HHA1_C1_15  H4_2_HHA1_C1_16  H4_2_HHA1_C1_17  H4_2_HHA1_C1_18  \
0              NaN              NaN              NaN              NaN
1              NaN              NaN              NaN              NaN
2              NaN              NaN              NaN              NaN
3              NaN              NaN              NaN              NaN
4              NaN              NaN              NaN              NaN

   H4_2_HHA1_C1_22  H4_2_HHA1_C1_24  H4_2_HHA1_C1_26  H4_2_HHA1_C1_29  \
0              NaN              NaN              NaN              NaN
1              NaN              NaN              NaN              NaN
2              NaN              NaN              NaN              NaN
3              NaN              NaN              NaN              NaN
4              NaN              NaN              NaN              NaN

   H4_2_HHA1_C1_30  H4_2_HHA1_C1_31  H4_2_HHA1_C1_3101  H4_2_HHA1_C1_32  \
0              NaN              NaN                NaN              NaN
1              NaN              NaN                NaN              NaN
2              NaN              NaN                NaN              NaN
3              NaN              NaN                NaN              NaN
4              NaN              NaN                NaN              NaN

   H4_2_HHA1_C1_33  H4_2_HHA1_C1_34  H4_2_HHA1_C1_35  H4_2_HHA1_C2_18  \
0              NaN              NaN              NaN              NaN
1              NaN              NaN              NaN              NaN
2              NaN              NaN              NaN              NaN
3              NaN              NaN              NaN              NaN
4              NaN              NaN              NaN              NaN


In [4]:
c1 = list(main_df)
c2 = []
for c in c1:
    if 'E3_2_HOS_C1_1' in c:
        c2.append(c)
        
rush_df = main_df[main_df['prvdr_num'] == '140119']
rush_df = rush_df.filter(items=['prvdr_num', 'fy_bgn_dt', 'fy_end_dt'] + c2)
#rush_df = rush_df[rush_df['fy_bgn_dt'].isin(['2019-07-01', '2020-07-01'])]
rush_df.head(40)

,prvdr_num,fy_bgn_dt,fy_end_dt,E3_2_HOS_C1_13,E3_2_HOS_C1_1,E3_2_HOS_C1_12,E3_2_HOS_C1_16,E3_2_HOS_C1_18,E3_2_HOS_C1_19,E3_2_HOS_C1_17,E3_2_HOS_C1_10,E3_2_HOS_C1_11,E3_2_HOS_C1_15
6943,140119,2020-07-01,2021-06-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11833,140119,2019-07-01,2020-06-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17944,140119,2018-07-01,2019-06-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22568,140119,2017-07-01,2018-06-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28431,140119,2016-07-01,2017-06-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39526,140119,2015-07-01,2016-06-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45272,140119,2014-07-01,2015-06-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
51971,140119,2013-07-01,2014-06-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
58233,140119,2012-07-01,2013-06-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
64397,140119,2011-07-01,2012-06-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
66577,140119,2010-07-01,2011-06-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
c1 = list(main_df)
c2 = []
for c in c1:
    if 'S10_C1_23' in c:
        c2.append(c)
        
rush_df = main_df[main_df['prvdr_num'] == '140119']
rush_df = rush_df.filter(items=['prvdr_num', 'fy_bgn_dt', 'fy_end_dt'] + c2)
#rush_df = rush_df[rush_df['fy_bgn_dt'].isin(['2019-07-01', '2020-07-01'])]
rush_df.head(40)

      prvdr_num  fy_bgn_dt  fy_end_dt   S10_C1_23
6943     140119 2020-07-01 2021-06-30  15369741.0
11833    140119 2019-07-01 2020-06-30  24305273.0
17944    140119 2018-07-01 2019-06-30  17170606.0
22568    140119 2017-07-01 2018-06-30  18034612.0
28431    140119 2016-07-01 2017-06-30  18114216.0
39526    140119 2015-07-01 2016-06-30  17480905.0
45272    140119 2014-07-01 2015-06-30  18690451.0
51971    140119 2013-07-01 2014-06-30  26256715.0
58233    140119 2012-07-01 2013-06-30  26276785.0
64397    140119 2011-07-01 2012-06-30  21321897.0
66577    140119 2010-07-01 2011-06-30  13525003.0

In [ ]:
rush_df = main_df[main_df['prvdr_num'] == '140119']
print('rush_df.shape:', rush_df.shape)
rush_df.to_excel('all_data/rush_hcris.xlsx', engine='xlsxwriter')

In [ ]:
to_replace = ['rpt_rec_num', 'prvdr_num', 'fi_num', 'rpt_stus_cd', 'fi_creat_dt', 
              'fy_bgn_dt', 'fy_end_dt', 'util_cd', 'trnsmtl_num', 'state', 
              'st_cty_cd', 'census', 'region', 'proc_dt', 'msa']

replacement = ['RPT_REC_NUM', 'PRVDR_NUM', 'FI_NUM', 'RPT_STUS_CD', 'FI_CREAT_DT', 
               'FY_BGN_DT', 'FY_END_DT', 'UTIL_CODE', 'TRNSMTL_NUM', 'STATE', 
               'ST_CTY_CD', 'CENSUS', 'REGION', 'PROC_DT', 'MSA']

main_df.rename(columns = {to_replace[0]: replacement[0], to_replace[1]: replacement[1],
                           to_replace[2]: replacement[2], to_replace[3]: replacement[3],
                           to_replace[4]: replacement[4], to_replace[5]: replacement[5],
                           to_replace[6]: replacement[6], to_replace[7]: replacement[7],
                           to_replace[8]: replacement[8], to_replace[9]: replacement[9],
                           to_replace[10]: replacement[10], to_replace[11]: replacement[11],
                           to_replace[12]: replacement[12], to_replace[13]: replacement[13],
                           to_replace[14]: replacement[14] }, inplace = True)

main_df.drop(['_NAME_'], axis=1, inplace=True)

In [ ]:
crosswalk_df = pd.read_csv('~/GitHub/HCRIS-databuilder/crosswalk/2552-10_SAS_FILE_RECORD_LAYOUT_AND_CROSSWALK_TO_96.csv', sep=',')
crosswalk_labels = crosswalk_df['10_FIELD_NAME'].tolist()
crosswalk_labels = [str(x).strip(' ') for x in crosswalk_labels]
crosswalk_df['10_FIELD_NAME'] = crosswalk_labels

In [ ]:
main_df_col_labels = list(main_df)
main_df_col_labels = [str(x).strip(' ') for x in main_df_col_labels]
print('main_df with NaN columns removed: (rows, columns) =', main_df.shape)

print('\nNumber of labels in the crosswalk:', len(crosswalk_labels))
print('Number of unique labels in the crosswalk:', len(list(set(crosswalk_labels))))

print('\nNumber of labels in the main_df:', len(main_df_col_labels))
print('Number of unique labels in the main_df:', len(list(set(main_df_col_labels))))

shared_labels = list(set(main_df_col_labels) & set(crosswalk_labels))
print('\nNumber of labels shared between the main dataframe and the crosswalk:', len(shared_labels))
shared_labels.append('File Date')
print(shared_labels[-8:])

In [ ]:
main_df2 = main_df[main_df.columns[main_df.columns.isin(shared_labels)]]

CODE = []
FIELD_DESCRIPTION = []
TYPE = []
SUBTYPE = []
#DATA_TYPE = []

col_labels = list(main_df2)
for lab in col_labels:
    if lab == 'File Date':
        CODE.append('File Date')
        FIELD_DESCRIPTION.append('File Date')
        TYPE.append('File Date')
        SUBTYPE.append('File Date')
    else:
        df_sub = crosswalk_df[crosswalk_df['10_FIELD_NAME'] == lab]
        CODE.append(df_sub['10_FIELD_NAME'].iloc[0])
        FIELD_DESCRIPTION.append(df_sub['FIELD DESCRIPTION '].iloc[0])
        TYPE.append(df_sub['TYPE'].iloc[0])
        SUBTYPE.append(df_sub['SUBTYPE'].iloc[0])
        #DATA_TYPE.append(df_sub['DATA_TYPE'].iloc[0])

SUBTYPE = pd.Series(SUBTYPE).fillna('').tolist()
TYPE = pd.Series(TYPE).fillna('').tolist()

for i, val in enumerate(SUBTYPE):
    if val == 'File Date':
        continue
    elif val == '':
        SUBTYPE[i] = str(FIELD_DESCRIPTION[i]) + ' ' + '(' + str(CODE[i]) + ')'
    else:
        SUBTYPE[i] = str(val) + ' ' + str(FIELD_DESCRIPTION[i]) + ' (' + str(CODE[i]) + ')'

df2 = pd.DataFrame([col_labels, FIELD_DESCRIPTION, TYPE, SUBTYPE], columns=col_labels)
main_df2 = pd.concat([df2, main_df2])

main_df2.head()

In [ ]:
main_df2.columns=pd.MultiIndex.from_arrays(main_df2.iloc[0:4].values)
main_df2 = main_df2.iloc[4:]

main_df3 = main_df2.loc[:, ~main_df2.columns.get_level_values(1).isin({float('NaN')})]
print(main_df3.shape)
main_df3.head(10)

In [ ]:
main_df4 = main_df3.copy(deep=True)
print(main_df4.shape)
main_df4 = main_df4[main_df4.columns.drop(list(main_df4.filter(regex='(Y/N)')))]
main_df4 = main_df4[main_df4.columns.drop(list(main_df4.filter(regex='costs?')))]
main_df4 = main_df4[main_df4.columns.drop(list(main_df4.filter(regex='NOT IN THIS FILE')))]
main_df4 = main_df4[main_df4.columns.drop(list(main_df4.filter(regex='Report Status Code')))]
main_df4 = main_df4[main_df4.columns.drop(list(main_df4.filter(regex='Urban/Rural Indicator at beginning')))]
#main_df4 = main_df4.dropna(axis=1, thresh=25000)
print(main_df4.shape)

In [ ]:
CMS_Gen_Info_df = pd.read_csv('~/GitHub/HCRIS-databuilder/GeoData/Hospital_General_Information.tsv', sep='\t')
print(list(CMS_Gen_Info_df))
CMS_Gen_Info_df.head(10)

In [ ]:
hospital_ls = main_df4.iloc[:, (main_df4.columns.get_level_values(0) == 'S2_1_C1_3')].T.values.tolist()[0]
id_ls = main_df4.iloc[:, (main_df4.columns.get_level_values(0) == 'PRVDR_NUM')].T.values.tolist()[0]

print(hospital_ls[0:4])
print(id_ls[0:4])

In [ ]:
lats = []
lons = []
Htypes = []
Ctypes = []

misses = 0
hits = 0
for i, h in enumerate(hospital_ls):
    
    #if i > 100: break   
    fid = id_ls[i]
    
    try:
        df = CMS_Gen_Info_df[CMS_Gen_Info_df['Facility ID'] == fid]
            
        loc = df['Location'].iloc[0]
        loc = loc.replace("POINT (","") 
        loc = loc.replace(")","")
        loc = loc.split(" ")
            
        lat = loc[1]
        lon = loc[0]
        lats.append(lat)
        lons.append(lon)
        
        htype = df['Hospital Type'].iloc[0]
        Htypes.append(htype)
        ctype = df['Hospital Ownership'].iloc[0]
        Ctypes.append(ctype)
        
        #hits += 1
        
    except:
        #misses += 1
        lats.append(float('NaN'))
        lons.append(float('NaN'))
        Htypes.append(float('NaN'))
        Ctypes.append(float('NaN'))

In [ ]:
main_df4[('Lat', 'Lat', 'Lat', 'Lat')] = lats
main_df4[('Lon', 'Lon', 'Lon', 'Lon')] = lons
main_df4[('Control type, text', 'Control type, text', 'Control type, text', 'Control type, text')] = Ctypes
main_df4[('Hospital type, text', 'Hospital type, text', 'Hospital type, text', 'Hospital type, text')] = Htypes
main_df4[('Num and Name', 'Num and Name', 'Num and Name', 'Num and Name')] = main_df4[('S2_1_C1_3', 'Hospital Name ', '', 'Hospital Name  (S2_1_C1_3)')] +' (' + main_df4[('PRVDR_NUM', 'Hospital Provider Number ', 'HOSPITAL IDENTIFICATION INFORMATION', 'Hospital Provider Number  (PRVDR_NUM)')] + ')'

In [ ]:
badnames = ['20994', float('NaN'), '-0007', '1', '330354', '4499 ACUSHNET AVENUE OPERATING COMPA',
           '4499 ACUSHNET AVENUE OPERATING COMPM']

main_df4 = main_df4[~main_df4[('S2_1_C1_3', 'Hospital Name ', '', 'Hospital Name  (S2_1_C1_3)')].isin(badnames)]

In [ ]:
main_df5 = main_df4.copy(deep=True)
print(main_df5.shape[1])
main_df5.dropna(axis=1, thresh = int(0.5*main_df5.shape[0]), inplace=True)
print(main_df5.shape[1])

In [ ]:
tdf = main_df4.filter(items=[('Lat', 'Lat', 'Lat', 'Lat'),
                             ('Lon', 'Lon', 'Lon', 'Lon'),
                             ('Control type, text', 'Control type, text', 'Control type, text', 'Control type, text'),
                             ('Hospital type, text', 'Hospital type, text', 'Hospital type, text', 'Hospital type, text'),
                             ('Num and Name', 'Num and Name', 'Num and Name', 'Num and Name'),
                             ('S3_1_C2_27', 'Total Facility', 'NUMBER OF BEDS', 'Total Facility (S3_1_C2_27)'),
                             ('S2_1_C2_2', 'Hospital State', '', 'Hospital State (S2_1_C2_2)'),
                            ], axis=1)

tdf.to_pickle('GenDat4App/GenDat4App.pkl', protocol=4)

In [ ]:
main_df4[('FY_END_DT', 'Fiscal Year End Date ', 'HOSPITAL IDENTIFICATION INFORMATION', 'Fiscal Year End Date  (FY_END_DT)')] = pd.to_datetime(main_df4[('FY_END_DT', 'Fiscal Year End Date ', 'HOSPITAL IDENTIFICATION INFORMATION', 'Fiscal Year End Date  (FY_END_DT)')])
main_df4.sort_values(by=[('Num and Name', 'Num and Name', 'Num and Name', 'Num and Name'),
                     ('FY_END_DT', 'Fiscal Year End Date ', 'HOSPITAL IDENTIFICATION INFORMATION', 'Fiscal Year End Date  (FY_END_DT)')],
                     ascending=[True, True])

In [ ]:
import re

numNname = sorted(list(set(main_df4[('Num and Name', 'Num and Name', 'Num and Name', 'Num and Name')].tolist())))

for i, val in enumerate(numNname):
    prvdr = re.sub('\ |\?|\.|\!|\/|\;|\:', '', val)

    tdf = main_df4[main_df4[('Num and Name', 'Num and Name', 'Num and Name', 'Num and Name')] == val]
    tdf.to_csv('provider_data/' + prvdr + '.csv')

In [ ]:
main_df4.to_pickle('all_data/HCRIS.pkl')

In [ ]:

report_categories = list(set(main_df4.columns.get_level_values(2).tolist()))
report_categories = [x for x in report_categories if str(x) != 'nan']
report_categories = [x for x in report_categories if str(x) != 'Lat']
report_categories = [x for x in report_categories if str(x) != 'Lon']
report_categories = [x for x in report_categories if str(x) != 'Lon']
report_categories = [x for x in report_categories if str(x) != 'Num and Name']
report_categories = [x for x in report_categories if str(x) != 'Hospital type, text']
report_categories = [x for x in report_categories if str(x) != '']
report_categories = [x for x in report_categories if str(x) != 'HOSPITAL IDENTIFICATION INFORMATION']

report_categories = [x for x in report_categories if str(x) != 'Control type, text']
report_categories = [x for x in report_categories if str(x) != 'HOSPITAL IDENTIFICATION INFORMATION']
report_categories = [x for x in report_categories if str(x) != 'HOSPITAL IDENTIFICATION INFORMATION']
report_categories.sort()

import csv

with open('GenDat4App/report_categories.csv', 'w+', newline='') as OUT:
    writer = csv.writer(OUT)
    writer.writerow(report_categories)
    
    
sub_categories = list(set(main_df4.columns.get_level_values(3).tolist()))
sub_categories.sort()

with open('GenDat4App/sub_categories.csv', 'w+', newline='') as OUT:
    writer = csv.writer(OUT)
    writer.writerow(sub_categories)